--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KanadeBlue/AuctionHoue
build-by-default: true
branches:
- main
projects:
  AuctionHoue:
      libs:
      - src: muqsit\invmenu
        version: ^4.6.5
    path: ""
...
